version: '3.4'

services:
  customerservice:
    image: ${DOCKER_REGISTRY-}customerservice
    build:
      context: .
      dockerfile: CustomerService/Dockerfile

  gate:
    image: ${DOCKER_REGISTRY-}gate
    build:
      context: .
      dockerfile: Gate/Dockerfile

